/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppointmentPreview: typeof import('./src/components/AppointmentPreview/AppointmentPreview.vue')['default']
    SVGIcon: typeof import('./src/components/SVGIcon/SVGIcon.vue')['default']
  }
}
